### ISSUE TITLE
docker compose compatibility

### ISSUE THREAD

**Issue by mashb1t** [ashleykleynhans/audiocraft-docker#3]
Hey @ashleykleynhans,

i was able to boot version 1 with a docker-compose.yml file, but with version 2.0.0 it's not possible anymore.

It would be great if you could help out :)

docker-compose.yml:

```
services:
  audiocraft:
    build:
      context: .
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

Console output:

> docker compose up
[+] Running 1/0
 ✔ Container audiocraft  Recreated                                                                                 0.0s
Attaching to audiocraft
audiocraft  |
audiocraft  | ==========
audiocraft  |
audiocraft  | == CUDA ==
audiocraft  | ======
audiocraft  | ====
audiocraft  |
audiocraft  | CUDA Version 11.8.0
audiocraft  |
audiocraft  |
audiocraft  | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
audiocraft  |
audiocraft  |
audiocraft  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
audiocraft  | By pulling and using the container, you accept the terms and conditions of this license:
audiocraft  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
audiocraft  |
audiocraft  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
audiocraft  |
audiocraft  |
audiocraft  | /opt/nvidia/nvidia_entrypoint.sh: /start.sh: /bin/bash^M: bad interpreter: No such file or directory
audiocraft  | /opt/nvidia/nvidia_entrypoint.sh: line 67: /start.sh: Success
audiocraft exited with code 0
